ekf_localization_node:
  frequency: 50                 # Hz output rate  # docs explain freq parameter
  sensor_timeout: 0.2           # seconds before a sensor is considered stale
  two_d_mode: true              # constrain Z, roll, pitch on flat terrain

  map_frame:      map
  odom_frame:     odom
  base_link_frame: base_link
  world_frame:    odom          # publish the odom→base_link transform
  publish_tf:     true
  publish_acceleration: true    # enable /accel/filtered stream

  ## ----------  Sphere IMU  ----------
  imu0: /imu_sphere                # topic from the driver
  imu0_differential: false
  imu0_relative:     false
  imu0_remove_gravitational_acceleration: true

  # 15-entry boolean mask: [x y z | R P Y | v_xyz | ω_xyz | a_xyz]
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                false, false, false,
                true,  true,  true]      # fuse yaw + linear accel only