# I2C Bus URI used to comunicate with I2C devices (default: "/dev/i2c-1")
bus_uri: "/dev/i2c-1"

# I2C address of MPU6050 (default: 0x68)
mpu_address: 0x68

# Frequency in Hertz wich IMU data is published (default: 30)
pub_rate: 100

# Frame if of IMU message (default: "imu")
frame_id: "sphere_imu"

# Offsets to fix wrong values caused by misalignment
# Sequence is (ax, ay, az, gx, gy, gz) (default: [0, 0, 0, 0, 0, 0])
# axes_offsets: [-1514, -1428, 1202, 109, 12, 17]
