# I2C Bus URI used to comunicate with I2C devices (default: "/dev/i2c-1")
bus_uri: "/dev/i2c-1"

# I2C address of MPU6050 (default: 0x68)
mpu_address: 0x68

# Frequency in Hertz wich IMU data is published (default: 30)
pub_rate: 500

# Frame if of IMU message (default: "imu")
frame_id: "head_imu"

# Offsets to fix wrong values caused by misalignment
# Sequence is (ax, ay, az, gx, gy, gz) (default: [0, 0, 0, 0, 0, 0])
axes_offsets: [-1514, -1428, 1202, 109, 12, 17]

# [INFO] [1746468582.685896383]: Final offset of Accel X axis = -1514
# [INFO] [1746468582.686087972]: Final offset of Accel Y axis = -1428
# [INFO] [1746468582.686230229]: Final offset of Accel Z axis = 1202
# [INFO] [1746468582.686359375]: Final offset of Gyro  X axis = 109
# [INFO] [1746468582.686495039]: Final offset of Gyro  Y axis = 12
# [INFO] [1746468582.686601704]: Final offset of Gyro  Z axis = 17


# PID constants used in calibration procedure
ki: 0.2 # (default: 0.1)
kp: 0.1 # (default: 0.1)

# The calibration process is finished when the error is aproximate zero with
# the precision set by delta (default: 0.5) 
delta: 0.5
