# Robot Configuration Parameters
max_vel_x:            0.40
min_vel_x:            0.00
max_vel_theta:        1.0
min_vel_theta:       -1.0
acc_lim_x:            0.6
acc_lim_theta:        5.0

holonomic_robot: false

# This also needed even if holonomic_robot is false
max_vel_y: 0.0
min_vel_y: 0.0
vy_samples: 0

# Goal Tolerance Parameters
xy_goal_tolerance: 0.3
yaw_goal_tolerance: 3
latch_xy_goal_tolerance: true

# Forward Simulation Parameters
sim_time: 2.0
vx_samples: 20
vy_samples: 20
vth_samples: 40
controller_frequency: 10.0

# Trajectory Scoring Parameters
path_distance_bias: 30.0
goal_distance_bias: 24.0
occdist_scale: 0.02
forward_point_distance: 0.325
stop_time_buffer: 0.2
scaling_speed: 0.3
max_scaling_factor: 1.0

# Oscillation Prevention Parameters
oscillation_reset_dist: 0.2

# Debugging
publish_traj_pc: true
publish_cost_grid_pc: true
