local_costmap:
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 5.0
  transform_tolerance: 0.5  

  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
