shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 3.0
controller_patience: 3.0
conservative_reset_dist: 3.0
planner_frequency: 1.0
oscillation_timeout: 5.0
oscillation_distance: 0.1

base_local_planner: dwa_local_planner/DWAPlannerROS

recovery_behavior_enabled: true
recovery_behaviors:
  - name: clear_costmap
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery